### ISSUE TITLE
Writeprotect comparefile

### ISSUE THREAD

**Issue by MelvisR** [mattiasclaesson/TuningSuites#8] opened 2017-05-21 05:54 UTC
To make sure users are editing the correct file and not the comparefile I suggest a change. 
Writeprotect the comparefile so that if only can be viewed and values copied. Perhaps just remove the save button?

**Comment by mattiasclaesson** [comment] 2017-05-28 20:39
yeah and the suites should also not crash when opening a readonly file....

**Comment by mattiasclaesson** [comment] 2017-05-28 20:43
If the file is read only deal with it without a crash at open.
If the file is a compare file, do not allow modifications.

Maybe a readonly flag? That dims the save button in viewers? Both new and old mapvievers? 
Same flag could be used to protect the read only file in both cases.

**Comment by MelvisR** [comment] 2017-08-10 07:16
Dim button sounds perfect.
Also noticed that Google drive goes nuts when working with the suites and all small changes. Syncs the file for every change and while syncing the file is read only = The suite complains...
Perhaps save to a temporary location and then write back when finished or similar?

**Comment by mattiasclaesson** [comment] 2017-08-12 10:04
It turned out a bit more strange than expected. 

Thers no crash at open. 

When I set a file to readonly, the suite seem to overwrite the file anyway. 

Confused...

/Mattias

**Comment by mattiasclaesson** [comment] 2017-10-30 19:06
Guess this is the cause;
its clearing the read-only flag.....funny trick!

**Comment by mattiasclaesson** [comment] 2017-11-05 19:11
T8suite, and probably the same in other suites.
In MapViewer*.designer.cs
            this.gridView1.OptionsBehavior.ReadOnly = true;
does the readonly trick.
Dimming save is irrelevant, since the datacells cannot be changed.

Maybe show somehow if its readonly or not in the gui. Normaly a readonly cell is with grey background but that would be useless. That leaves the title I guess, or some icon in the toolbar?

T7suite does show that the bin is readonly in the left-lower corner. Implement in T8suite?

**Comment by mattiasclaesson** [comment] 2017-11-07 20:47
It was allready fixed and active in the t5suite code! IMapViewer.IsCompareViewer()

**Comment by mattiasclaesson** [comment] 2017-11-09 20:18
Fixed in t7 and t8 suites!

**Closed by mattiasclaesson** 2017-11-09 20:18 UTC
